// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PPE_Models;

namespace PPE_Models.Migrations
{
    [DbContext(typeof(SQLiteDBContext))]
    partial class SQLiteDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("PPE_Models.Stock", b =>
                {
                    b.Property<string>("StockID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Inventory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Packaging")
                        .HasColumnType("TEXT");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("QuantityBackordered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StockNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfIssue")
                        .HasColumnType("TEXT");

                    b.Property<long>("UnitOfIssueUnitSmallest")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vendor")
                        .HasColumnType("TEXT");

                    b.HasKey("StockID");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("PPE_Models.StockHistory", b =>
                {
                    b.Property<string>("StockID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("StockID", "DateTime");

                    b.ToTable("StockHistory");
                });

            modelBuilder.Entity("PPE_Models.TrackedStock", b =>
                {
                    b.Property<string>("StockID")
                        .HasColumnType("TEXT");

                    b.HasKey("StockID");

                    b.ToTable("TrackedStocks");
                });
#pragma warning restore 612, 618
        }
    }
}
